/** Declaration file generated by dts-gen */

export class Kafka {
    constructor(...args: any[]);

    admin(...args: any[]): void;

    consumer(...args: any[]): void;

    logger(...args: any[]): void;

    producer(...args: any[]): void;

}

export const AssignerProtocol: {
    MemberAssignment: {
        decode: any;
        encode: any;
    };
    MemberMetadata: {
        decode: any;
        encode: any;
    };
};

export const CompressionTypes: {
    GZIP: number;
    LZ4: number;
    None: number;
    Snappy: number;
};

export const logLevel: {
    DEBUG: number;
    ERROR: number;
    INFO: number;
    NOTHING: number;
    WARN: number;
};

export namespace CompressionCodecs {
}

export namespace Kafka {
    namespace prototype {
        function admin(...args: any[]): void;

        function consumer(...args: any[]): void;

        function logger(...args: any[]): void;

        function producer(...args: any[]): void;

    }

}

export namespace PartitionAssigners {
    function roundRobin({ cluster }: any): any;

}

